version: "3.7"

services:
  backend:
    build:
      context: ./backend
    command: ["yarn", "start"]
    volumes:
      - ./backend:/dist
    ports:
      - 3000:3000

  proxy:
    image: nginx:mainline
    restart: always
    volumes: 
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/ssl:/etc/nginx/ssl
    ports:
      - 443:443
      - 80:80
    depends_on:
      - backend