version: "3.7"

services:
  backend:
    build:
      context: ./backend
    command: ["yarn", "start"]
    volumes:
      - ~/config.json:/dist/src/config/config.json
    ports:
      - 13000:13000

  proxy:
    image: nginx:mainline
    restart: always
    volumes: 
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ~/ssl:/etc/nginx/ssl
    ports:
      - 443:443
      - 80:80
    depends_on:
      - backend